- _target_: verl.tasks.math_like_task.MathLikeTaskConfig
  name: math_like_task
  loading_params:
    args:
      - MathMindsAGI/OpenMathReasoning_ready
    kwargs:
      split: test
  problem_key: problem
  answer_key: answer

  max_samples: 1000

  prompt_template: '{}\n\nPlease reason step by step, and put your final answer within \\boxed{{}}.'
  system_prompt: null

  data_source: "OpenMath"
